export {
  DEFAULT_CLIP_DURATION,
  DEFAULT_CROP,
  DEFAULT_HISTORY_LIMIT,
  DEFAULT_OUTPUT_SETTINGS,
  DEFAULT_TEXT_ANIMATION,
  DEFAULT_TEXT_STYLE,
  DEFAULT_TRACK_DEFINITIONS,
  DEFAULT_TRANSFORM,
  MAX_PLAYBACK_RATE,
  MIN_CLIP_DURATION,
  MIN_CROP_SIZE,
  MIN_PLAYBACK_RATE,
  PROJECT_HARD_MAX_DURATION,
  PROJECT_SCHEMA_VERSION,
  TRACK_TYPES,
  TRACK_TYPE_VALUES,
} from './projectConstants.js';

export {
  calculateProjectDuration,
  clampNumber,
  cloneProject,
  createAudioClip,
  createClip,
  createEditorId,
  createEditorProject,
  createImageClip,
  createTextClip,
  createTrack,
  createVideoClip,
  deserializeProject,
  isEditorProject,
  normalizeCrop,
  normalizeOutputSettings,
  normalizeProject,
  normalizeTransform,
  roundTimelineTime,
  sanitizeJsonValue,
  serializeProject,
} from './projectModel.js';

export {
  addTrackToProject,
  attachExtractedAudioClip,
  finalizeProjectChange,
  findClipById,
  getActiveClipsAtTime,
  getAllClips,
  getClipEnd,
  getClipLocation,
  getPrimaryTrackByType,
  getTrackById,
  getTracksByType,
  insertClip,
  moveClip,
  removeClipById,
  replaceClipWithSplit,
  retimeClipPlaybackRate,
  rippleDeleteClipById,
  sortClipsByTimeline,
  splitClip,
  trimClip,
  updateClipById,
  updateTrackById,
} from './projectUtils.js';

export {
  EDITOR_ACTIONS,
  canRedo,
  canUndo,
  createInitialEditorState,
  editorActions,
  editorReducer,
} from './editorReducer.js';

export {
  bulkRowToProject,
  getBulkProjectTrack,
  hydrateBulkProjectDurations,
  mergeBulkRowPatchIntoProject,
  projectToBulkRow,
  syncBulkRowContent,
} from './projectAdapters.js';
